const root = document.getElementById("root");
const div = document.createElement("div");
div.classList.add("container");
root.appendChild(div);
const h1 = document.createElement("h1");
div.appendChild(h1);
h1.innerHTML = "blog title";
const img = document.createElement("img");
document.getElementsByTagName("img").src = "hackanm.gif";
div.appendChild(img);
const p = document.createElement("p");
p.innerHTML = "lorem ipsum dolor sit amet";
div.appendChild(p);
const button = document.createElement("button");
button.innerHTML = "read more";
div.appendChild(button);
div.style.backgroundColor = "grey";
div.style.display = "flex";
div.style.justifyContent = "center";
div.style.flexDirection = "column";
